volumes:
  db-store:
  psysh-store:

configs:
  db-config:
    file: ./infra/docker/mysql/my.cnf

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./src/server
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - ${WEB_PUBLISHED_PORT:-8000}:80
    volumes:
      - type: bind
        source: ./src/server
        target: /workspace
    
  front:
    build:
      context: .
      dockerfile: ./infra/docker/front/Dockerfile
    ports:
      - ${FRONT_PUBLISHED_PORT:-3000}:3000
    volumes:
      - type: bind
        source: ./src/client
        target: /app
    tty: true
    environment:
      # こっちのオプションでは動作せず
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PUBLISHED_PORT:-3306}:3306
    configs:
      - source: db-config
        target: /etc/my.cnf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./infra/docker/mysql/initdb
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-movie-app}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}

  mailpit:
    image: axllent/mailpit
    ports:
      - ${MAILPIT_PUBLISHED_PORT:-8025}:8025
